name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - test
  pull_request:
    branches:
      - test
      - master

jobs:
  code-quality:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 .

  automated-testing:
    if: github.ref == 'refs/heads/test' || github.event_name == 'pull_request' && github.base_ref == 'test'
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

  trigger-jenkins:
    if: github.ref == 'refs/heads/master'
    needs: automated-testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Jenkins job
        run: |
          # Add the command to trigger your Jenkins job, for example:
          # curl -X POST "JENKINS_JOB_URL/buildWithParameters?token=YOUR_TOKEN"
          echo "Jenkins job triggered"
